import { boolean, integer, jsonb, numeric, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })

export const hrmsProfiles = pgTable('hrms_profiles', { id: text('id').primaryKey(), userId: text('userId').notNull(), role: text('role').notNull().default('employee'), organization: text('organization').notNull().default('PeoplePilot'), department: text('department'), faceAuthEnabled: boolean('face_auth_enabled').notNull().default(false), createdAt: timestamp('created_at').notNull().defaultNow(), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const hrmsEmployees = pgTable('hrms_employees', { id: text('id').primaryKey(), userId: text('userId').notNull(), employeeCode: text('employee_code').notNull(), name: text('name').notNull(), department: text('department').notNull(), status: text('status').notNull().default('active'), attendanceRate: numeric('attendance_rate').notNull().default('100'), createdAt: timestamp('created_at').notNull().defaultNow() })
export const hrmsPluginHealth = pgTable('hrms_plugin_health', { id: text('id').primaryKey(), userId: text('userId').notNull(), pluginKey: text('plugin_key').notNull(), status: text('status').notNull(), metric: text('metric').notNull(), checkedAt: timestamp('checked_at').notNull().defaultNow() })
export const hrmsJobs = pgTable('hrms_jobs', { id: text('id').primaryKey(), userId: text('userId').notNull(), jobKey: text('job_key').notNull(), status: text('status').notNull(), progress: integer('progress').notNull().default(0), errorMessage: text('error_message'), updatedAt: timestamp('updated_at').notNull().defaultNow() })
export const hrmsAuditEvents = pgTable('hrms_audit_events', { id: text('id').primaryKey(), userId: text('userId').notNull(), eventType: text('event_type').notNull(), severity: text('severity').notNull().default('info'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at').notNull().defaultNow() })
