'use client'

import { useMemo, useState } from 'react'
import { Activity, Bell, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, Download, Eye, FileBarChart2, LayoutDashboard, LogOut, Menu, Search, ScanFace, Settings2, ShieldCheck, Sparkles, Users, X } from 'lucide-react'

const modules = [
  ['Dashboard', LayoutDashboard, 'Overview'], ['CEO Dashboard', BriefcaseBusiness, 'Overview'], ['Salary Intelligence', CircleDollarSign, 'Overview'],
  ['People & Headcount', Users, 'Workforce'], ['Recruitment', BriefcaseBusiness, 'Workforce'], ['Payroll & Compensation', CircleDollarSign, 'Workforce'], ['Attendance & Leave', CalendarDays, 'Workforce'], ['Performance', Activity, 'Workforce'], ['Compliance & Statutory', ShieldCheck, 'Workforce'], ['Learning & Development', Sparkles, 'Workforce'],
  ['Background Processing', Activity, 'Operations'], ['Monitoring & Observability', Activity, 'Operations'], ['Approval Workflows', CheckCircle2, 'Operations'], ['Reports & Exports', FileBarChart2, 'Intelligence'], ['HR Intelligence', Sparkles, 'Intelligence'],
] as const

const workspaceSettings = [
  ['Organization', 'Company identity, fiscal year, and workspace profile'], ['Entities', 'Legal entities, payroll ownership, and cost centers'], ['Departments & Teams', 'Team hierarchy, managers, and workforce structure'], ['Locations', 'Offices, time zones, holidays, and work policies'], ['Users', 'User directory, invitations, and account status'], ['Roles & Permissions', 'Role-based access and approval authority'], ['Security', 'MFA, session policy, IP allowlists, and PII masking'], ['Approval Workflows', 'Configurable approval chains and escalation rules'], ['Attendance Configuration', 'Shifts, grace periods, biometric devices, and exceptions'], ['Leave Configuration', 'Leave types, accruals, balances, and holiday calendars'], ['Payroll Configuration', 'Pay cycles, earnings, deductions, and statutory rules'], ['Recruitment Configuration', 'Hiring stages, requisitions, scorecards, and offers'], ['Performance Configuration', 'Review cycles, goals, ratings, and calibration'], ['Learning Configuration', 'Programs, certifications, skills, and compliance training'], ['Compliance Configuration', 'Statutory calendars, filings, and control owners'], ['Notifications', 'Email, SMS, in-app alerts, and escalation preferences'], ['Reports', 'Scheduled reports, access, retention, and export formats'], ['Integrations', 'Payroll, finance, identity, communication, and API connections'], ['AI Configuration', 'AI assistants, data boundaries, and human approvals'], ['Data Management', 'Retention, imports, exports, anonymization, and backups'], ['Audit Logs', 'Immutable activity history, reviewers, and retention'], ['System Settings', 'Regional defaults, maintenance, feature flags, and system health'],
] as const

const entities = [
  ['Corporate HQ', '286', '₹1.42Cr', '₹4.8L', '₹1.31Cr'], ['Technology Services', '312', '₹1.58Cr', '₹7.9L', '₹1.47Cr'], ['Operations & Logistics', '274', '₹96.4L', '₹5.1L', '₹89.2L'], ['Sales & Distribution', '176', '₹66.2L', '₹0.8L', '₹61.4L'],
]

function Metric({ label, value, change, good = false }: { label: string; value: string; change: string; good?: boolean }) {
  return <div className="rounded-xl border border-[#294666] bg-[#0d1f35] p-5"><p className="text-xs text-[#7899c0]">{label}</p><p className="mt-2 text-2xl font-semibold text-[#edf5ff]">{value}</p><p className={`mt-2 text-xs ${good ? 'text-[#2dd4bf]' : 'text-[#f3ae55]'}`}>{change}</p></div>
}

function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return <section className="rounded-xl border border-[#294666] bg-[#0d1f35] p-5"><div className="mb-5"><h3 className="font-semibold text-[#edf5ff]">{title}</h3><p className="mt-1 text-xs text-[#7899c0]">{subtitle}</p></div>{children}</section>
}

export default function HrmsDashboard({ userName = 'Alex Morgan' }: { userName?: string }) {
  const [active, setActive] = useState('Dashboard')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const [faceAuth, setFaceAuth] = useState(false)
  const [searchOpen, setSearchOpen] = useState(false)
  const [viewAs, setViewAs] = useState('HR Business Partner')
  const [viewAsOpen, setViewAsOpen] = useState(false)
  const [live, setLive] = useState(true)
  const [exportOpen, setExportOpen] = useState(false)
  const activeModule = useMemo(() => modules.find((item) => item[0] === active) ?? modules[0], [active])
  const initials = userName.split(' ').map((name) => name[0]).join('').slice(0, 2)

  function exportCsv() {
    const csv = `HRMS Report\nModule,${active}\nView,${viewAs}\nGenerated,${new Date().toISOString()}\n\nEntity,Employees,Actual Salary,Overtime,Net Paid\n${entities.map((row) => row.join(',')).join('\n')}`
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }))
    const link = document.createElement('a'); link.href = url; link.download = `${active.toLowerCase().replaceAll(' ', '-')}-report.csv`; link.click(); URL.revokeObjectURL(url); setExportOpen(false)
  }

  return <main className="min-h-screen bg-[#071321] text-[#edf5ff]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[278px] flex-col border-r border-[#203655] bg-[#0c1b30] px-4 py-5 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-3"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-[#23c7b5] text-xs font-bold text-[#06202a]">HR</div><div><p className="font-semibold">HRMS Platform</p><p className="text-[11px] text-[#7595bd]">Enterprise HR Suite</p></div></div><button className="lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <nav className="mt-8 flex-1 overflow-y-auto pr-1">{['Overview', 'Workforce', 'Operations', 'Intelligence'].map((group) => <div key={group} className="mb-6"><p className="px-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#5f84b7]">{group}</p><div className="mt-2 space-y-1">{modules.filter((item) => item[2] === group).map(([label, Icon]) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13px] ${active === label ? 'bg-[#173257] text-[#48dfca]' : 'text-[#9ab5d9] hover:bg-[#122744]'}`}><Icon size={16} />{label}</button>)}</div></div>)}</nav>
      <div className="border-t border-[#203655] pt-4"><button onClick={() => setSettingsOpen(true)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-[#9ab5d9] hover:bg-[#122744]"><Settings2 size={16} />Workspace settings</button><button onClick={() => { window.location.href = '/sign-in' }} className="mt-1 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-[#9ab5d9] hover:bg-[#122744]"><LogOut size={16} />Log out</button><div className="mt-4 flex items-center gap-3 px-2"><div className="flex size-8 items-center justify-center rounded-full bg-[#23c7b5] text-xs font-semibold text-[#06202a]">{initials}</div><div><p className="text-xs font-semibold">{userName}</p><p className="text-[10px] text-[#7595bd]">Workspace admin</p></div></div></div>
    </aside>
    <div className="lg:pl-[278px]"><header className="flex min-h-[74px] items-center justify-between border-b border-[#203655] bg-[#0c1b30] px-5 sm:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><div><p className="text-[11px] text-[#7595bd]">Enterprise HR Platform</p><h1 className="text-lg font-semibold">{activeModule[0]}</h1></div></div><div className="flex items-center gap-2"><div className="relative hidden md:block"><button onClick={() => setSearchOpen(!searchOpen)} className="flex items-center gap-2 rounded-lg border border-[#274568] bg-[#0a1729] px-3 py-2 text-xs text-[#7899c0]"><Search size={14} />Search modules</button>{searchOpen && <input autoFocus onKeyDown={(event) => { if (event.key === 'Enter') { setActive('Reports & Exports'); setSearchOpen(false) } }} placeholder="Search reports..." className="absolute right-0 top-11 z-50 w-56 rounded-lg border border-[#294666] bg-[#0d2038] px-3 py-2 text-xs outline-none" />}</div><div className="relative"><button onClick={() => setNotificationsOpen(!notificationsOpen)} aria-label="Notifications" className="relative rounded-lg border border-[#274568] p-2 text-[#9ab5d9]"><Bell size={16} /><span className="absolute right-1 top-1 size-1.5 rounded-full bg-[#f3ae55]" /></button>{notificationsOpen && <div className="absolute right-0 top-11 z-50 w-80 rounded-xl border border-[#294666] bg-[#0d2038] p-4 shadow-xl"><div className="flex justify-between"><b className="text-sm">Live notifications</b><span className="rounded-full bg-[#164b4c] px-2 py-1 text-[10px] text-[#4de0c9]">7 active</span></div><div className="mt-3 space-y-2 text-xs text-[#9ab5d9]"><p className="rounded-lg bg-[#122b43] p-3">Payroll processed for 1,048 employees</p><p className="rounded-lg bg-[#122b43] p-3">12 attendance exceptions require review</p><p className="rounded-lg bg-[#122b43] p-3">Security verification passed</p><p className="rounded-lg bg-[#122b43] p-3">3 leave requests await approval</p></div></div>}</div><div className="relative hidden lg:block"><button onClick={() => setViewAsOpen(!viewAsOpen)} className="flex items-center gap-1 rounded-lg border border-[#274568] px-3 py-2 text-xs text-[#9ab5d9]"><Eye size={14} />{viewAs}<ChevronDown size={13} /></button>{viewAsOpen && <div className="absolute right-0 top-11 z-50 w-48 rounded-lg border border-[#294666] bg-[#0d2038] p-2"><p className="px-3 py-2 text-[10px] uppercase text-[#5f84b7]">View dashboard as</p>{['HR Business Partner', 'CEO', 'Manager', 'Employee'].map((role) => <button key={role} onClick={() => { setViewAs(role); setViewAsOpen(false) }} className="block w-full rounded px-3 py-2 text-left text-xs text-[#9ab5d9] hover:bg-[#173257]">{role}</button>)}</div>}</div></div></header>
      <div className="mx-auto max-w-[1550px] px-5 py-7 sm:px-8"><section className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-3"><p className="font-mono text-xs text-[#74a8df]">Data refreshed · live · {viewAs}</p><span className="flex items-center gap-1 rounded-full bg-[#0d2844] px-2 py-1 text-[10px] text-[#7899c0]"><span className={`size-2 rounded-full ${live ? 'bg-[#2dd4bf] animate-pulse' : 'bg-[#f3ae55]'}`} />{live ? 'Monitoring on' : 'Paused'}</span></div><h2 className="text-3xl font-semibold tracking-tight">{active === 'Dashboard' ? `Dashboard — ${viewAs}` : active}</h2><p className="mt-1 text-sm text-[#7899c0]">Real-time operational insights, decisions, and workflows.</p></div><div className="flex flex-wrap gap-2"><div className="relative"><button onClick={() => setExportOpen(!exportOpen)} className="rounded-lg border border-[#294666] px-3 py-2 text-xs text-[#a9c3e4]"><Download size={14} className="mr-1 inline" />Export</button>{exportOpen && <div className="absolute right-0 top-11 z-30 rounded-lg border border-[#294666] bg-[#0d2038] p-2"><button onClick={exportCsv} className="block w-full rounded px-3 py-2 text-left text-xs hover:bg-[#173257]">Download CSV</button><button onClick={() => { setExportOpen(false); window.print() }} className="block w-full rounded px-3 py-2 text-left text-xs hover:bg-[#173257]">Export as PDF</button><button onClick={() => { setExportOpen(false); window.print() }} className="block w-full rounded px-3 py-2 text-left text-xs hover:bg-[#173257]">Print report</button></div>}</div><button onClick={() => setLive(!live)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${live ? 'bg-[#23c7b5] text-[#06202a]' : 'border border-[#294666] text-[#a9c3e4]'}`}><Activity size={14} className="mr-1 inline" />{live ? 'Live' : 'Start live'}</button><button onClick={() => setFaceAuth(true)} className="rounded-lg bg-[#79a8ff] px-3 py-2 text-xs font-semibold text-white"><ScanFace size={14} className="mr-1 inline" />Face verify</button></div></section>
      {active === 'Dashboard' || active === 'CEO Dashboard' || active === 'Salary Intelligence' ? <ExecutiveContent salary={active !== 'Dashboard'} /> : <ModuleContent active={active} />}</div></div>
    {settingsOpen && <Modal title="Workspace settings" onClose={() => setSettingsOpen(false)}><div className="mb-5 rounded-lg border border-[#294666] bg-[#102944] p-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#48dfca]">Enterprise control center</p><p className="mt-2 text-sm text-[#9ab5d9]">Configure governance, people operations, security, and data controls from one workspace.</p></div><div className="grid max-h-[52vh] gap-2 overflow-y-auto pr-1 sm:grid-cols-2">{workspaceSettings.map(([setting, description], index) => <button key={setting} onClick={() => setActive(setting)} className="group flex items-start justify-between gap-3 rounded-lg border border-[#294666] bg-[#102944] p-3 text-left hover:border-[#48dfca]"><span><span className="block text-sm font-semibold text-[#edf5ff]">{index + 1}. {setting}</span><span className="mt-1 block text-xs leading-5 text-[#7899c0]">{description}</span></span><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#2dd4bf] group-hover:text-[#48dfca]" /></button>)}</div><div className="mt-5 flex items-center justify-between"><span className="text-xs text-[#7899c0]">Changes apply to the live HRMS workspace.</span><button onClick={() => setSettingsOpen(false)} className="rounded-lg bg-[#23c7b5] px-4 py-2 text-sm font-semibold text-[#06202a]">Save settings</button></div></Modal>}
    {faceAuth && <Modal title="Face authentication" onClose={() => setFaceAuth(false)}><div className="rounded-xl border border-[#294666] bg-[#102944] p-6 text-center"><div className="mx-auto flex size-20 items-center justify-center rounded-full border-2 border-[#2dd4bf] bg-[#0b263b]"><ScanFace size={40} className="text-[#2dd4bf]" /></div><h4 className="mt-4 font-semibold">Secure identity verification</h4><p className="mt-2 text-sm text-[#8eadd3]">Position your face in the frame to verify access to sensitive HR data.</p><button onClick={() => setFaceAuth(false)} className="mt-5 rounded-lg bg-[#23c7b5] px-5 py-2.5 text-sm font-semibold text-[#06202a]">Start verification</button></div></Modal>}
  </main>
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020812]/80 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-2xl rounded-2xl border border-[#31547c] bg-[#0d2038] p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#48dfca]">HRMS control center</p><h3 className="mt-2 text-xl font-semibold">{title}</h3></div><button onClick={onClose} aria-label="Close dialog"><X size={18} /></button></div>{children}</div></div> }

function ExecutiveContent({ salary = false }: { salary?: boolean }) { return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Current month payroll" value="₹4.82Cr" change="+6.4% vs last month" good /><Metric label="Last month payroll" value="₹4.53Cr" change="Processed successfully" good /><Metric label="Actual salary" value="₹4.63Cr" change="96.1% of gross payroll" good /><Metric label="Overtime payout" value="₹18.6L" change="+8.2% this month" /></section><section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Panel title={salary ? 'Actual salary and OT trend' : 'Payroll trend — current vs last month'} subtitle="Live monthly salary movement"><div className="flex h-56 items-end gap-3 border-b border-[#203655] px-3 sm:gap-7">{[58, 65, 71, 78, 86, 94].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full max-w-12 rounded-t bg-[#2dd4bf]" style={{ height: `${height}%` }} /><span className="font-mono text-[10px] text-[#7394bb]">{['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'][index]}</span></div>)}</div></Panel><Panel title="Executive statistics" subtitle="Real-time business indicators"><div className="space-y-4">{[['Payroll accuracy', '99.7%'], ['Employees paid', '1,048'], ['Entities processed', '4 / 4'], ['Budget utilization', '87.2%'], ['Pending approvals', '12']].map(([label, value]) => <div key={label} className="flex justify-between border-b border-[#1d3552] pb-3 text-sm"><span className="text-[#8eadd3]">{label}</span><b>{value}</b></div>)}</div></Panel></section><section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_1fr]"><Panel title="Entity salaries report" subtitle="Actual salary, overtime, and net paid by entity"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-xs"><thead className="border-b border-[#294666] text-[#6f91ba]"><tr>{['Entity', 'Employees', 'Actual salary', 'OT salary', 'Net paid'].map((head) => <th key={head} className="pb-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-[#1d3552]">{entities.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell} className="py-3 text-[#cfe0f4]">{cell}</td>)}</tr>)}</tbody></table></div></Panel><Panel title="Detail report" subtitle="Decision-ready payroll observations"><div className="space-y-3 text-sm text-[#cfe0f4]"><p className="rounded-lg bg-[#122b43] p-3"><b className="text-[#48dfca]">On track.</b> All entities completed salary processing.</p><p className="rounded-lg bg-[#122b43] p-3"><b className="text-[#f3ae55]">Attention.</b> Operations overtime increased 8.2% this month.</p><p className="rounded-lg bg-[#122b43] p-3"><b className="text-[#79a8ff]">Forecast.</b> Next month payroll projected at ₹4.96Cr.</p></div></Panel></section></> }

function ModuleContent({ active }: { active: string }) { return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label={`${active} records`} value="1,248" change="+12.4% this month" good /><Metric label="Completed workflows" value="94.8%" change="Above target" good /><Metric label="Pending actions" value="27" change="Needs attention" /><Metric label="Data freshness" value="98.4%" change="Live monitoring" good /></section><section className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Panel title={`${active} overview`} subtitle="Interactive operational view with live data"><div className="space-y-4">{['System health and data quality', 'Approvals and pending actions', 'Recent activity and audit trail', 'Team performance against target'].map((item, index) => <div key={item} className="flex items-center justify-between rounded-lg border border-[#203655] bg-[#102944] p-4"><div className="flex items-center gap-3"><div className={`size-2 rounded-full ${index === 1 ? 'bg-[#f3ae55]' : 'bg-[#2dd4bf]'}`} /><span className="text-sm text-[#cfe0f4]">{item}</span></div><span className="text-xs text-[#7899c0]">{index === 1 ? '27 pending' : 'Healthy'}</span></div>)}</div></Panel><Panel title="Live statistics" subtitle="Updated automatically"><div className="space-y-5"><div><div className="mb-2 flex justify-between text-xs"><span className="text-[#9ab5d9]">Completion rate</span><b className="text-[#2dd4bf]">94.8%</b></div><div className="h-2 rounded-full bg-[#16324b]"><div className="h-2 w-[95%] rounded-full bg-[#2dd4bf]" /></div></div><div><div className="mb-2 flex justify-between text-xs"><span className="text-[#9ab5d9]">Data quality</span><b className="text-[#79a8ff]">98.4%</b></div><div className="h-2 rounded-full bg-[#16324b]"><div className="h-2 w-[98%] rounded-full bg-[#79a8ff]" /></div></div><button className="w-full rounded-lg border border-[#294666] px-3 py-2.5 text-xs text-[#a9c3e4] hover:border-[#48dfca]">Open detailed report</button></div></Panel></section></> }
